"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GameState = exports.PointType = exports.QuestionType = void 0;
var QuestionType;
(function (QuestionType) {
    QuestionType["MULTIPLE_CHOICE"] = "MULTIPLE_CHOICE";
    QuestionType["TRUE_FALSE"] = "TRUE_FALSE";
    QuestionType["INPUT"] = "INPUT";
    QuestionType["PUZZLE"] = "PUZZLE";
    QuestionType["POLL"] = "POLL";
    QuestionType["WORD_CLOUD"] = "WORD_CLOUD";
    QuestionType["OPEN_ENDED"] = "OPEN_ENDED";
    QuestionType["AUDIO_QUIZ"] = "AUDIO_QUIZ";
    QuestionType["IMAGE_QUIZ"] = "IMAGE_QUIZ";
    QuestionType["PIN_ANSWER"] = "PIN_ANSWER";
    QuestionType["SLIDER"] = "SLIDER";
    QuestionType["FLASHCARD"] = "FLASHCARD";
    QuestionType["SCALE"] = "SCALE";
    QuestionType["DROP_PIN"] = "DROP_PIN";
})(QuestionType || (exports.QuestionType = QuestionType = {}));
var PointType;
(function (PointType) {
    PointType["NORMAL"] = "NORMAL";
    PointType["HALF"] = "HALF";
    PointType["DOUBLE"] = "DOUBLE";
    PointType["NONE"] = "NONE";
})(PointType || (exports.PointType = PointType = {}));
var GameState;
(function (GameState) {
    GameState[GameState["HOME"] = 0] = "HOME";
    GameState[GameState["BROWSE"] = 1] = "BROWSE";
    GameState[GameState["AUTH"] = 2] = "AUTH";
    GameState[GameState["CREATING"] = 3] = "CREATING";
    GameState[GameState["EDITOR"] = 4] = "EDITOR";
    GameState[GameState["LOBBY"] = 5] = "LOBBY";
    GameState[GameState["QUESTION_INTRO"] = 6] = "QUESTION_INTRO";
    GameState[GameState["QUESTION_ACTIVE"] = 7] = "QUESTION_ACTIVE";
    GameState[GameState["ANSWER_REVEAL"] = 8] = "ANSWER_REVEAL";
    GameState[GameState["LEADERBOARD"] = 9] = "LEADERBOARD";
    GameState[GameState["PODIUM"] = 10] = "PODIUM";
    GameState[GameState["DASHBOARD"] = 11] = "DASHBOARD";
    GameState[GameState["JOINING"] = 12] = "JOINING";
    GameState[GameState["SETTINGS"] = 13] = "SETTINGS";
})(GameState || (exports.GameState = GameState = {}));
