import React from 'react';
import {
  BsLightningChargeFill,
  BsPlayFill,
  BsPeopleFill,
  BsChevronRight,
  BsPerson,
  BsKey,
  BsPower,
  BsGearFill,
  BsShieldLock,
  BsPersonFill,
  BsPlusLg,
  BsJournalX,
  BsCpu,
  BsPencilFill,
  BsTrash3Fill,
  BsExclamationTriangleFill,
  BsXLg,
  BsArrowUp,
  BsArrowDown,
  BsXCircle,
  BsCheckLg,
  BsPlusCircle,
  BsStars,
  BsLightningFill,
  BsChevronUp,
  BsChevronDown,
  BsGripVertical,
  BsLockFill,
  BsSendFill,
  BsCpuFill,
  BsExclamationOctagon,
  BsSearch,
  BsArrowLeft,
  BsArrowRight,
  BsTrophy,
  BsCoin,
  BsStar,
  BsStarFill,
  BsShare,
} from 'react-icons/bs';

interface IconProps {
  name: string;
  className?: string;
  style?: React.CSSProperties;
}

const iconMap: Record<string, React.ComponentType<any>> = {
  'bi-lightning-charge-fill': BsLightningChargeFill,
  'bi-play-fill': BsPlayFill,
  'bi-people-fill': BsPeopleFill,
  'bi-chevron-right': BsChevronRight,
  'bi-person': BsPerson,
  'bi-key': BsKey,
  'bi-power': BsPower,
  'bi-gear-fill': BsGearFill,
  'bi-shield-lock': BsShieldLock,
  'bi-person-fill': BsPersonFill,
  'bi-plus-lg': BsPlusLg,
  'bi-journal-x': BsJournalX,
  'bi-cpu': BsCpu,
  'bi-pencil-fill': BsPencilFill,
  'bi-trash3-fill': BsTrash3Fill,
  'bi-exclamation-triangle-fill': BsExclamationTriangleFill,
  'bi-x-lg': BsXLg,
  'bi-arrow-up': BsArrowUp,
  'bi-arrow-down': BsArrowDown,
  'bi-x-circle': BsXCircle,
  'bi-check-lg': BsCheckLg,
  'bi-plus-circle': BsPlusCircle,
  'bi-stars': BsStars,
  'bi-lightning-fill': BsLightningFill,
  'bi-chevron-up': BsChevronUp,
  'bi-chevron-down': BsChevronDown,
  'bi-grip-vertical': BsGripVertical,
  'bi-lock-fill': BsLockFill,
  'bi-send-fill': BsSendFill,
  'bi-cpu-fill': BsCpuFill,
  'bi-exclamation-octagon': BsExclamationOctagon,
  'bi-search': BsSearch,
  'bi-arrow-left': BsArrowLeft,
  'bi-arrow-right': BsArrowRight,
  'bi-trophy': BsTrophy,
  'bi-coin': BsCoin,
  'bi-star': BsStar,
  'bi-star-fill': BsStarFill,
  'bi-share': BsShare,
};

export const Icon: React.FC<IconProps> = ({ name, className, style }) => {
  const IconComponent = iconMap[name];
  
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found in icon map`);
    return null;
  }
  
  return <IconComponent className={className} style={style} />;
};

// Individual exports for direct usage
export {
  BsLightningChargeFill,
  BsPlayFill,
  BsPeopleFill,
  BsChevronRight,
  BsPerson,
  BsKey,
  BsPower,
  BsGearFill,
  BsShieldLock,
  BsPersonFill,
  BsPlusLg,
  BsJournalX,
  BsCpu,
  BsPencilFill,
  BsTrash3Fill,
  BsExclamationTriangleFill,
  BsXLg,
  BsArrowUp,
  BsArrowDown,
  BsXCircle,
  BsCheckLg,
  BsPlusCircle,
  BsStars,
  BsLightningFill,
  BsChevronUp,
  BsChevronDown,
  BsGripVertical,
  BsLockFill,
  BsSendFill,
  BsCpuFill,
  BsExclamationOctagon,
  BsSearch,
  BsArrowLeft,
  BsArrowRight,
  BsTrophy,
  BsCoin,
  BsStar,
  BsStarFill,
  BsShare,
};
